name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: gh-secrets-manager

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/gh-secrets-manager
    steps:
      - uses: actions/checkout@v3
        with:
          path: gh-secrets-manager

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Install dependencies
        run: go mod download

      - name: Build
        env:
          COMMIT_HASH: ${{ github.sha }}
        run: |
          mkdir -p bin
          go build -ldflags="-X gh-secrets-manager/pkg/version.CommitHash=$COMMIT_HASH" -o bin/gh-secrets-manager ./cmd/gh-secrets-manager